name: build

on: push
jobs: 
  build-nodes:
    runs-on: ubuntu-latest
    container: node-16  
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: npm install
      - run: node app.js
      
