name: build

on: push

jobs: 
  build-nodes:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      
      - name: Verify Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm install

      - name: Run the application
        run: node app.js

      
