name: build

on: push

jobs: 
  build-nodes:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    container:
      image: node:16
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      
      - name: Verify Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm install

      - name: Start the application in the background
        run: |
          nohup node app.js & # Start the app in the background
          sleep 5 # Wait for a few seconds to ensure the server is up

      - name: Test server response
        run: |
          curl -f http://localhost:3000 || exit 1 # Check if the server is running and responding

      - name: Stop the application
        run: |
          pid=$(netstat -tuln | grep ':3000' | awk '{print $7}' | cut -d"/" -f1)
          kill $pid || echo "Server not running"
